// --- APRENDO CON VIDEOS: videos del canal del profesor John Jairo Estrada asociados a cada pestaña ---
// Solo videos del canal; comprobados en YouTube (listado del canal) en octubre de 2026. Los títulos se muestran corregidos.
const VIDEOS_CANAL = {
  canal: "https://www.youtube.com/channel/UCe_8YXWBojXgfgaiQODPWTg",
  // [tema, pestaña relacionada (o null), qué se aprende, videos]
  temas: [
    ["Presentación del curso y de la aplicación", "introduccion", "Para qué sirven las matemáticas en la técnica agropecuaria y qué contiene esta aplicación.", ["7eu-h1H9Jug", "FAUSouiv6dQ"]],
    ["Los siete módulos del curso", "guias_modulos_pdf", "Una clase por módulo: importancia de las matemáticas en el agro, conjuntos numéricos, regla de tres, fracciones y decimales, potenciación y proporciones, ecuaciones y conversión de unidades.", ["GwkOku6-wK4", "S9aFBc4mZts", "jzHb8EC6ztk", "M_dPUEl8xy0", "FAVEFS31OhQ", "dm7CIPXkjcE", "vSUPGoafIWI"]],
    ["Guías: cómo iniciar cada módulo", "guias_modulos_pdf", "Qué leer, qué ver y qué practicar en cada una de las siete guías en PDF.", ["Bhdu8CkkNos", "VXP5XSKenLg", "evfGX-bOUfg", "L56y5Wu-vmY", "UhJPnROmcNA", "iQFqI9iq5OE", "PEd7Zcm9xio"]],
    ["Regla de tres", "r3directa_cat", "Regla de tres directa, inversa y compuesta con problemas agropecuarios.", ["QOO3NczV_dg", "-MjFh-aIBnQ", "drsfOPmwddk", "tZqsQ1WhmqI"]],
    ["Ecuaciones cuadráticas en la finca", "algebra", "Problemas de parcelas, corrales y estanques que llevan a una ecuación cuadrática.", ["vrWH6JnlB4I"]],
    ["Conceptos geométricos", "geometria_cat", "Perímetros, áreas y volúmenes claves, y la línea recta en el planteo de problemas.", ["WadkpkbyfRY", "XUDgJga7zSI", "PBb-jFGTN0I"]],
    ["Despeje de variables", "despeje_cat", "Cómo aislar una incógnita en fórmulas de distintos campos de las ciencias.", ["ZorbD4FDix8", "YnwrGKNJKX0"]],
    ["Razonamiento deductivo", "razonamiento_cat", "Problemas lógicos resueltos con tablas de deducción.", ["X2X7ckrTW_Y", "RSXhqPLTKgQ"]],
    ["Sumas verticales", "sumas", "Suma en columnas con y sin decimales, con acarreo.", ["679tKktW4G4", "0Pq9WjZ3E48"]],
    ["Restas verticales", "restas", "Resta en columnas con préstamo.", ["M2ytCNJPI2M"]],
    ["Multiplicación", "mults", "Multiplicación por una y dos cifras y su relación con la suma en columnas.", ["gHNWX-7tbJY"]],
    ["División", "divs", "División entre números y división por una cifra.", ["MhuDuTe8bZ0", "mTrLfZ9e028"]],
    ["Fracciones y potencias", "fracciones", "Operaciones con fracciones, operaciones mixtas y potenciación con fracciones.", ["0ghKPQplRaE", "lmHpxDThezI", "39pPj2mzZ9E"]],
    ["Factorización de trinomios", "factorizacion_cat", "Factorización de expresiones cuadráticas, también con la técnica de Po-Shen Loh.", ["PbSb8ifiJBk", "NicDdU1HdBU"]],
    ["Signos de agrupación y orden de operaciones", "expr", "Paréntesis, corchetes y llaves, y el orden correcto de las operaciones.", ["AwS2nmRv-U4", "Kio46hWuFJ0"]],
    ["Planteo de problemas con el método de Pólya", "probs", "Los cuatro pasos de Pólya aplicados a problemas del agro y de edades.", ["u8F-ZnBaXhA", "C01tANWnSNU", "11bNyZW9tlY", "SlDNOnmV7q8"]],
    ["Conversión de unidades", null, "Cambio de unidades de longitud, área, volumen y masa (módulo 7).", ["cC8CXtesWNg"]]
  ],
  titulos: {
    "7eu-h1H9Jug": "Introducción al curso Matemáticas para la Técnica Agropecuaria",
    "FAUSouiv6dQ": "Contenido de la aplicación Matemática agropecuaria",
    "GwkOku6-wK4": "Módulo 1: importancia de las matemáticas en el agro",
    "S9aFBc4mZts": "Módulo 2: importancia de los conjuntos numéricos en el agro",
    "jzHb8EC6ztk": "Módulo 3: regla de tres simple directa, inversa y compuesta",
    "M_dPUEl8xy0": "Módulo 4: fracciones y decimales",
    "FAVEFS31OhQ": "Módulo 5: potenciación y proporciones",
    "dm7CIPXkjcE": "Módulo 6: ecuaciones matemáticas aplicadas en la tecnología agropecuaria",
    "vSUPGoafIWI": "Módulo 7: conversión de unidades en la tecnología agropecuaria",
    "Bhdu8CkkNos": "Guía del módulo 1: ¿cómo iniciar? ¿qué realizar?",
    "VXP5XSKenLg": "Guía del módulo 2: ¿cómo iniciar? ¿qué realizar?",
    "evfGX-bOUfg": "Guía del módulo 3: ¿cómo iniciar? ¿qué realizar?",
    "L56y5Wu-vmY": "Guía del módulo 4: ¿cómo iniciar? ¿qué realizar?",
    "UhJPnROmcNA": "Guía del módulo 5: ¿cómo iniciar? ¿qué realizar?",
    "iQFqI9iq5OE": "Guía del módulo 6: ¿cómo iniciar? ¿qué realizar?",
    "PEd7Zcm9xio": "Guía del módulo 7: ¿cómo iniciar? ¿qué realizar?",
    "QOO3NczV_dg": "Regla de tres directa para agropecuarios",
    "-MjFh-aIBnQ": "Regla de tres inversa para agropecuarios",
    "drsfOPmwddk": "Regla de tres directa e inversa en temas agropecuarios",
    "tZqsQ1WhmqI": "Regla de tres compuesta para agropecuarios",
    "vrWH6JnlB4I": "Problemas que generan expresiones cuadráticas",
    "WadkpkbyfRY": "Conceptos geométricos claves en el planteo y solución de problemas",
    "XUDgJga7zSI": "Áreas y volúmenes: conceptos geométricos claves",
    "PBb-jFGTN0I": "Cuándo aplicar el concepto de línea recta",
    "ZorbD4FDix8": "Despeje de variables, parte 1: aplicaciones en diversos campos de las ciencias",
    "YnwrGKNJKX0": "Despeje de variables, parte 2",
    "X2X7ckrTW_Y": "Problema lógico 1 (Tecnología Agropecuaria)",
    "RSXhqPLTKgQ": "Problema lógico 1: las profesiones",
    "679tKktW4G4": "Sumas verticales de números sin decimales",
    "0Pq9WjZ3E48": "Sumas verticales de números con decimales",
    "M2ytCNJPI2M": "Diferencia (resta) vertical entre números",
    "gHNWX-7tbJY": "Multiplicación por una y dos cifras y su relación con la suma en columnas",
    "MhuDuTe8bZ0": "División entre números",
    "mTrLfZ9e028": "División de números por una cifra",
    "0ghKPQplRaE": "Operaciones aritméticas con fracciones",
    "lmHpxDThezI": "Operaciones mixtas con fracciones",
    "39pPj2mzZ9E": "Potenciación con fracciones",
    "PbSb8ifiJBk": "Técnica de Po-Shen Loh para factorizar",
    "NicDdU1HdBU": "Factorización de trinomios cuadráticos",
    "AwS2nmRv-U4": "Manejo de paréntesis, corchetes y llaves para operar con números",
    "Kio46hWuFJ0": "Orden de las operaciones aritméticas",
    "u8F-ZnBaXhA": "Planteo y solución de problemas con el método de G. Pólya",
    "C01tANWnSNU": "Método de G. Pólya: problemas de edades",
    "11bNyZW9tlY": "Metodología de G. Pólya aplicada en el agro",
    "SlDNOnmV7q8": "Cuatro ejemplos del método de G. Pólya",
    "cC8CXtesWNg": "Conversión de unidades"
  }
};
